# Generated by Django 4.2.7 on 2025-10-04 16:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('budget_min', models.DecimalField(decimal_places=2, help_text='Minimum budget in dollars', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_max', models.DecimalField(decimal_places=2, help_text='Maximum budget in dollars', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the lead')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'), models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx'), models.Index(fields=['assigned_to'], name='leads_lead_assigne_3f8857_idx')],
            },
        ),
    ]
