# Generated by Django 4.2.7 on 2025-10-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
