# Generated by Django 4.2.7 on 2025-10-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(),
        ),
    ]
