# Generated by Django 4.2.7 on 2025-10-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_first_name_alter_lead_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_assigne_3f8857_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='notes',
        ),
    ]
