# Generated by Django 4.2.7 on 2025-10-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_lead_leads_lead_assigne_3f8857_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='updated_at',
        ),
    ]
