# Generated by Django 4.2.7 on 2025-10-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_lead_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='created_by',
        ),
    ]
