# Generated by Django 4.2.7 on 2025-10-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_activity_lead_deleted_at_lead_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='leads_activ_activit_93b425_idx',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='leads_activ_created_de4f8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_created_302c6d_idx',
        ),
        migrations.AddField(
            model_name='lead',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_interest',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('zillow', 'Zillow'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note')]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget_max',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget_min',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('negotiation', 'Negotiation'), ('closed', 'Closed'), ('lost', 'Lost')], default='new', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email',), name='unique_active_lead_email'),
        ),
    ]
